### ISSUE TITLE
LDAPS with certcheck=false 

### ISSUE THREAD

**Issue by Azylog** [h44z/wg-portal#12]
Hello,
I just tried to use a SSL (not StartTLS) server as admin users' source.

It seems there's no respect of the certcheck configuration option in this specific case :
```
WARN[2021-04-21 07:26:43] failed to setup LDAP connection, LDAP features disabled
ERRO[2021-04-21 07:26:43] skipping provider registration: unable to open ldap connection: LDAP Result Code 200 "Network Error": x509: certificate signed by unknown authority
```

As go-ldap seems to able nicely ldap(s) urls, you could simply add the tls.Config to the first call of first ldap.DialURL.
Or create the tls.Config at the start at the ldap.Open function and use it for every subsequent DialURL.

As previously said, I can't really write a formal PR as I have no clue of golang, sorry.

**Comment by h44z** [comment]
Thanks, nice catch. I just pushed the changes to the master branch. If you are using the docker image, can you test the changes using the latest tag (h44z/wg-portal:latest)? (Might take a few minutes for docker-hub to rebuild the image...)

**Comment by Azylog** [comment]
Ok, waiting for the new image on docker-hub.

**Comment by Azylog** [comment]
Still the same errors :
```
INFO[2021-04-21 08:45:06] starting WireGuard Portal Server [latest-e65a4a8]... 
[...]
WARN[2021-04-21 08:45:06] failed to setup LDAP connection, LDAP features disabled 
ERRO[2021-04-21 08:45:06] skipping provider registration: unable to open ldap connection: LDAP Result Code 200 "Network Error": x509: certificate signed by unknown authority
```

I don't have more debug info with LOG_LEVEL=trace.

My LDAP config (in case I missed something) : 
```
      # LDAP Settings
      - LDAP_ENABLED=true
      - LDAP_TYPE=OpenLDAP
      - LDAP_URL=ldaps://ldap.company.com:636
      - LDAP_BASEDN=dc=company,dc=com
      - LDAP_USER=uid=viewonly,cn=users,cn=accounts,dc=company,dc=com
      - LDAP_PASSWORD=strongpasswordofcourse
      - LDAP_ADMIN_GROUP=cn=vpnadmins,cn=groups,cn=accounts,dc=company,dc=com
      - LDAP_STARTTLS=false
      - LDAP_CERT_VALIDATION=false
```

Same result with LDAP_STARTTLS=true, which is not surprising.

As configuring a LDAPS server is some kind of nightmare, I can provide a readonly account to ldap.company.com for debugging purposes. Thinking of it, only the hostname would be enough, no need to be able to bind.

**Comment by h44z** [comment]
I see. I have overlooked the ldap connection code of the auth provider, the previous commit only updated the ldap connection that is used for the user-synchronization.

**Comment by Azylog** [comment]
OK, let see if 7042523 resolve this issue.

**Comment by Azylog** [comment]
It works like a charm : no more errors in logs and loggued successully with a LDAP user !

Thanks a lot a for this quick fix and sorry for pointing out the wrong function (or half of it ;-)
