### ISSUE TITLE
OAuth SSO with google gives 404/wrong redirect

### ISSUE THREAD

**Issue by justinas-b** [h44z/wg-portal#317]
Hey! I am struggling to setup SSO through OAuth, At the moment my configuration looks like:

```
...
auth:
  callback_url_prefix: https://wg.mydomain.net/api/v0
  oauth:
    - id: google
      provider_name: google
      display_name: Google
      base_url: https://accounts.google.com/
      client_id: [REDACTED]
      client_secret: [REDACTED]
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      user_info_url: https://openidconnect.googleapis.com/v1/userinfo
      #redirect_url: https://wg.mydomain.net/api/v0/google/callback
      scopes:
        - openid
        - email
        - profile
      field_map:
        email: email
        firstname: name
        user_identifier: preferred_username
        is_admin: roles
      registration_enabled: false
```

When i try to login using google, i am getting 404 error

```
Nov 04 11:12:47 vpn-01 wg-portal-amd64[586117]:
  time="2024-11-04T11:12:47+02:00"
  level=warning
  clientIP=10.100.1.4
  dataLength=0
  hostname=vpn-01
  latency=1
  method=GET
  path="/api/v0https://wg.mydomain.net/api/v0/google/init"
  referer="https://wg.mydomain.net/app/"
  statusCode=404
  userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15"
  msg="10.100.1.4 - vpn-01 [04/Nov/2024:11:12:47 +0200] \"GET /api/v0https://wg.mydomain.net/api/v0/google/init\" 404 0 \"https://wg.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15\"
    (1ms)"
```

I think the redirect url is broken, specifically this line ` path="/api/v0https://wg.mydomain.net/api/v0/google/init"`. Any ideas how to fix this?

**Comment by justinas-b** [comment]
If i set `callback_url_prefix: ""`, redirection seems to be fixed:
`https://wg.mydomain.net/api/v0/google/init?redirect=true&return=https%3A%2F%2Fwg.mydomain.net%2F%23%2Flogin`

However i am still getting 404

**Comment by justinas-b** [comment]
I am running v2 alpha.2

**Comment by dithmer** [comment]
Same happened with OAuth with Entra ID. 

I am working on a fix right now.

**Comment by bonddim** [comment]
@dithmer , this is my working config:
### config.yaml
```yaml
config:
  web:
    external_url: https://${WG_PORTAL_DNS_HOSTNAME}
  auth:
    callback_url_prefix: "https://${WG_PORTAL_DNS_HOSTNAME}/api/v0"
    oidc:
      - id: azure
        provider_name: azure
        display_name: Login with Azure
        registration_enabled: true
        base_url: "https://login.microsoftonline.com/${TENANT_ID}/v2.0"
        client_id: "${WG_PORTAL_CLIENT_ID}"
        client_secret: "${WG_PORTAL_CLIENT_SECRET}"
        extra_scopes:
          - profile
          - email
        field_map:
          user_identifier: email
          is_admin: admin
```
### Application config on Entra ID
![image](https://github.com/user-attachments/assets/6a34f741-d424-4fef-b208-717edb9fdeb3)

### Api permissions
![image](https://github.com/user-attachments/assets/0a0c8bd2-d68a-4f83-b8bc-0c91f270eef1)

### App role for admins
![image](https://github.com/user-attachments/assets/9a734627-667f-46f8-85b0-fb3987a985b8)

### Assign Admin role to group in **Enterprise applications**
![image](https://github.com/user-attachments/assets/ba75014f-6396-4759-8906-6b0fceab6c30)

### Additional token config (probably not needed)
![image](https://github.com/user-attachments/assets/8e6e4391-69af-4196-9776-610fcae3c4e4)

**Comment by bonddim** [comment]
As you may see, I'm using `oidc` not `oauth`.
`oauth` also didn't work for me, when I tried it.

**Comment by h44z** [comment]
This should be fixed now =)

I have also added a sample config for plain oauth:

```yaml
...

auth:
  oauth:
    - id: google_plain_oauth
      provider_name: google3
      display_name: Login with</br>Google3
      client_id: another-client-id-1234.apps.googleusercontent.com
      client_secret: A_CLIENT_SECRET
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      user_info_url: https://openidconnect.googleapis.com/v1/userinfo
      scopes:
        - openid
        - email
        - profile
      field_map:
        email: email
        firstname: name
        user_identifier: sub
        is_admin: roles
      registration_enabled: true
```

**Comment by justinas-b** [comment]
When we could expect new release to happen with this fix?

**Comment by bonddim** [comment]
> When we could expect new release to happen with this fix?

Try to use image with tag *latest* or *master*

**Comment by justinas-b** [comment]
Which image you are referring? Under releases I see that the latest one is from 2024 April https://github.com/h44z/wg-portal/releases

**Comment by bonddim** [comment]
Version with fix is not released yet.
You may build binary by yourself or download from [action artifacts](https://github.com/h44z/wg-portal/actions/runs/12610841299)

**Comment by h44z** [comment]
new alpha version is now available: https://github.com/h44z/wg-portal/releases/tag/v2.0.0-alpha.3

**Comment by justinas-b** [comment]
Hmm, I am still getting errors while trying to login using google:

```
auth:
  oauth:
    - id: google
      provider_name: google
      display_name: Google
      # base_url: https://accounts.google.com/
      client_id: something-something.apps.googleusercontent.com
      client_secret: my-secret-key
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      # redirect_url: /google/callback
      user_info_url: https://openidconnect.googleapis.com/v1/userinfo
      scopes:
        - openid
        - email
        - profile
      field_map:
        email: email
        firstname: name
        user_identifier: sub
        is_admin: roles
      registration_enabled: true
```

It throws `redirect_uri_mismatch` error (https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch).

In logs I see following event when trying to login using google:
```
Jan 09 23:33:37 vpn-01 wg-portal-amd64[2556383]: time="2025-01-09T23:33:37+02:00" level=info msg="10.100.1.4 - vpn-01 [09/Jan/2025:23:33:37 +0200] \"GET /api/v0/auth/login/google/init\" 302 333 \"https://vpn.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (1ms)" clientIP=10.100.1.4 dataLength=333 hostname=vpn-01 latency=1 method=GET path=/api/v0/auth/login/google/init referer="https://vpn.mydomain.net/app/" statusCode=302 userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
```

**Comment by h44z** [comment]
Have you allowed the correct callback url in your google application? It should be somethig like: https://your.domain/api/v0/auth/login/google/callback

**Comment by justinas-b** [comment]
Ahhh... 🤦  I had typo there ... thanks for pointing this out 😊
btw, is it possible to set a user who logged in using OAuth as an admin?

**Comment by h44z** [comment]
> Ahhh... 🤦 I had typo there ... thanks for pointing this out 😊 btw, is it possible to set a user who logged in using OAuth as an admin?

As OAuth users are overwritten every time they log in, manually editing properties of such users is not possible. But you can use specific fields in the user-info response to manage admin users:

The field you map with 'is_admin' is evaluated as a boolean, if the value of that field matches "true", the user is treated as admin.

**Comment by justinas-b** [comment]
So I have custom attribute defined in workspace:
<img width="1441" alt="image" src="https://github.com/user-attachments/assets/381fb1f8-01ac-4a63-b923-6bffe2b5b30b" />

And I set that attribute to true for a user:
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/050a4d55-24aa-44bb-8e8b-c0ae8c547537" />

but when that user logs in, it is not granted admin role. When I check with admin user, I see following:
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/bc496e5e-b639-4e92-84d9-62f61d84153a" />


My `field_map` looks like this now:
```
      field_map:
        email: email
        firstname: name
        user_identifier: email
        is_admin: wgportal_admin
```

**Comment by h44z** [comment]
@justinas-b: the user data was not updated correctly after OAuth logins - thus, the change of the is_admin flag did not take effect.
This should be fixed now - all other configuration looks good!

**Comment by justinas-b** [comment]
Thanks @h44z ! By any chance I could get a new alpha release created with this fix?

**Comment by h44z** [comment]
> Thanks @h44z ! By any chance I could get a new alpha release created with this fix?

check out **v2.0.0-beta.1**: https://github.com/h44z/wg-portal/releases/tag/v2.0.0-beta.1

**Comment by justinas-b** [comment]
@h44z still same issue - user is not marked as admin. Should I try manually dropping the user from database so that it would be re-created?

**Comment by justinas-b** [comment]
Trace logging seems to be broken, it gives only `info` level messages. If I turn on `debug` logging, I get below, but I cannot find anything useful here:


```
Jan 13 22:28:26 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":79,"hostname":"vpn-01","latency":464,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:26 +0200] \"GET /api/v0/auth/login/google/callback\" 302 79 \"https://accounts.google.com/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (464ms)","path":"/api/v0/auth/login/google/callback","referer":"https://accounts.google.com/","statusCode":302,"time":"2025-01-13T22:28:26+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:27 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":39,"hostname":"vpn-01","latency":1,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:27 +0200] \"GET /\" 301 39 \"https://accounts.google.com/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (1ms)","path":"/","referer":"https://accounts.google.com/","statusCode":301,"time":"2025-01-13T22:28:27+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:27 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":1313,"hostname":"vpn-01","latency":1,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:27 +0200] \"GET /app/\" 200 1313 \"https://accounts.google.com/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (1ms)","path":"/app/","referer":"https://accounts.google.com/","statusCode":200,"time":"2025-01-13T22:28:27+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:27 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":192,"hostname":"vpn-01","latency":1,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:27 +0200] \"GET /api/v0/config/frontend.js\" 200 192 \"https://wgportal.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (1ms)","path":"/api/v0/config/frontend.js","referer":"https://wgportal.mydomain.net/app/","statusCode":200,"time":"2025-01-13T22:28:27+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:27 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":647860,"hostname":"vpn-01","latency":26,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:27 +0200] \"GET /app/assets/index-C1L6upED.css\" 200 647860 \"https://wgportal.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (26ms)","path":"/app/assets/index-C1L6upED.css","referer":"https://wgportal.mydomain.net/app/","statusCode":200,"time":"2025-01-13T22:28:27+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:29 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":2050856,"hostname":"vpn-01","latency":2296,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:29 +0200] \"GET /app/assets/index-CV0k1T8f.js\" 200 2050856 \"https://wgportal.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (2296ms)","path":"/app/assets/index-CV0k1T8f.js","referer":"https://wgportal.mydomain.net/app/","statusCode":200,"time":"2025-01-13T22:28:29+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:31 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":10556,"hostname":"vpn-01","latency":1,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:31 +0200] \"GET /app/img/header-logo.png\" 200 10556 \"https://wgportal.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (1ms)","path":"/app/img/header-logo.png","referer":"https://wgportal.mydomain.net/app/","statusCode":200,"time":"2025-01-13T22:28:31+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:31 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":30,"hostname":"vpn-01","latency":1,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:31 +0200] \"GET /api/v0/csrf\" 200 30 \"https://wgportal.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (1ms)","path":"/api/v0/csrf","referer":"https://wgportal.mydomain.net/app/","statusCode":200,"time":"2025-01-13T22:28:31+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:31 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":140,"hostname":"vpn-01","latency":1,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:31 +0200] \"GET /api/v0/auth/session\" 200 140 \"https://wgportal.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (1ms)","path":"/api/v0/auth/session","referer":"https://wgportal.mydomain.net/app/","statusCode":200,"time":"2025-01-13T22:28:31+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:31 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":125,"hostname":"vpn-01","latency":1,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:31 +0200] \"GET /api/v0/auth/providers\" 200 125 \"https://wgportal.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (1ms)","path":"/api/v0/auth/providers","referer":"https://wgportal.mydomain.net/app/","statusCode":200,"time":"2025-01-13T22:28:31+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:31 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":140,"hostname":"vpn-01","latency":1,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:31 +0200] \"GET /api/v0/auth/session\" 200 140 \"https://wgportal.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (1ms)","path":"/api/v0/auth/session","referer":"https://wgportal.mydomain.net/app/","statusCode":200,"time":"2025-01-13T22:28:31+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
Jan 13 22:28:31 vpn-01 wg-portal-amd64[2670953]: {"clientIP":"10.100.1.4","dataLength":101,"hostname":"vpn-01","latency":4,"level":"info","method":"GET","msg":"10.100.1.4 - vpn-01 [13/Jan/2025:22:28:31 +0200] \"GET /api/v0/config/settings\" 200 101 \"https://wgportal.mydomain.net/app/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15\" (4ms)","path":"/api/v0/config/settings","referer":"https://wgportal.mydomain.net/app/","statusCode":200,"time":"2025-01-13T22:28:31+02:00","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"}
```

**Comment by h44z** [comment]
@justinas-b I have just pushed a new update that should fix the update bug.

There should be a line like this in the log:

`time="2025-01-13T22:12:39+01:00" level=trace msg="updated user someuser@gmail.com with data from external authentication provider, admin user: false"
`

The "admin user" part should indicate if the is_admin attribute matching was ok... If the user is granted admin rights, the log should contain "true".

To enable trace logging, set the following config:

```yaml
advanced:
  log_level: trace
```

New release v2.0.0-beta.2 should be available any moment =)

**Comment by justinas-b** [comment]
nope, I am still facing issues with `trace` logging:
```
root@vpn-01:/opt/wg-portal# /opt/wg-portal/wg-portal-amd64 -h
INFO[0000] Starting WireGuard Portal V2...
INFO[0000] WireGuard Portal version: v2.0.0-beta.2-c211c56
```

I see some `trace` events in the beginning, when service starts, however later on when user initiates login using google there are no trace/debug events appearing, only info level.

**Comment by bonddim** [comment]
@justinas-b ,
I'm not familiar with Google IAM and Oauth, but I can confirm that fix provided by @h44z 100% works.
Log with my Azure OIDC (added comments with performed checks):
```
INFO[0000] Starting WireGuard Portal V2...              
INFO[0000] WireGuard Portal version: v2.0.0-beta.2-c211c56 
INFO[0000] Log Level: trace
...truncated...
 ### first login - user is not in admin's group
TRAC[0013] registered user OjziaFYeozR-2Ia4OhH7fg3iyHdkkWdkokvAQ7FBo7E from external authentication provider, admin user: false
### added user to admin group on Azure and re-login
TRAC[0103] updated user OjziaFYeozR-2Ia4OhH7fg3iyHdkkWdkokvAQ7FBo7E with data from external authentication provider, admin user: true 
### removed user from admin group and re-login
TRAC[0172] updated user OjziaFYeozR-2Ia4OhH7fg3iyHdkkWdkokvAQ7FBo7E with data from external authentication provider, admin user: false 
```
As you may see, user role was changed appropriately to changes made in Azure.

Try to use custom claim and request it in wg-portal by adding to `scope` config.

**Comment by justinas-b** [comment]
I have finally managed to obtain this trace message:

```
Jan 15 11:18:03 vpn-01 wg-portal-amd64[2715458]: {"level":"trace","msg":"updated user j.balinskas@mydomain.net with data from external authentication provider, admin user: false","time":"2025-01-15T11:18:03+02:00"}
Jan 15 11:30:21 vpn-01 wg-portal-amd64[2715458]: {"level":"trace","msg":"registered user v.pavardenis@mydomain.net from external authentication provider, admin user: false","time":"2025-01-15T11:30:21+02:00"}
```

It seems that for OAUTH authentication, this message is printed only when the user logs in for the first time, as subsequent logins do not generate this trace message.

I think google does not include custom attributes when using standard OAuth scopes like `userinfo.profile` or `userinfo.email`. Isn't it the case that i should create a domain wide delegation for `https://www.googleapis.com/auth/admin.directory.user.readonly` scope, and the application itself should then fetch this attrinbute upon user login?

**Comment by bonddim** [comment]
Probably this will help somehow

https://cloud.google.com/identity-platform/docs/how-to-configure-custom-claims

**Comment by justinas-b** [comment]
This is for Google's Identity Platform, which is part of GCP and is a paid service (not part of Google Workspace).

I could fall back on OIDC authentication, but I would like to use a `groups` claim and grant admin access if a user is a member of a particular group. Does the current implementation allow me to achieve this?

**Comment by bonddim** [comment]
Unfortunately not. This field should be bool compatible, while `groups` will return something like list.

**Comment by h44z** [comment]
> This is for Google's Identity Platform, which is part of GCP and is a paid service (not part of Google Workspace).
> 
> I could fall back on OIDC authentication, but I would like to use a `groups` claim and grant admin access if a user is a member of a particular group. Does the current implementation allow me to achieve this?

I have to think about a solution for OAuth groups... would for sure be a nice addition to the current boolean-only admin flag

**Comment by bonddim** [comment]
> > This is for Google's Identity Platform, which is part of GCP and is a paid service (not part of Google Workspace).
> 
> > 
> 
> > I could fall back on OIDC authentication, but I would like to use a `groups` claim and grant admin access if a user is a member of a particular group. Does the current implementation allow me to achieve this?
> 
> 
> 
> I have to think about a solution for OAuth groups... would for sure be a nice addition to the current boolean-only admin flag

Yep. Providers use `roles` property for this usually.

**Comment by justinas-b** [comment]
So by default, user will have a claim which would contain list of groups, something like:
```
...
"email": "j.doe@example.com",
"user_groups": [
  "group1",
  "group2",
  "group3"
],
...
```

If we could have some additional configuration flags in `config.yaml` like below, i think that would be wonderful:
```
groups_claim_name: "user_groups"
admin_group_name: "group3"
```

**Comment by h44z** [comment]
@justinas-b config looks good, the retrieved data also looks ok. I will check that.

**Comment by bonddim** [comment]
@justinas-b , 
you need to escape dot in your regex:  `^wgportal-admins@mydomain\.net$`

**Comment by justinas-b** [comment]
Still getting this log message:
`Jan 20 21:47:59 vpn-01 wg-portal-amd64[2868754]: {"level":"trace","msg":"registered user j.balinskas@mydomain.net from external authentication provider, admin user: false","time":"2025-01-20T21:47:59+02:00"}`

My config now looks ike:
```
oidc:
    - id: dex
      provider_name: dex-google
      display_name: Google
      base_url: https://dex.mydomain.net
      client_id: REDACTED
      client_secret: REDACTED
      extra_scopes:
        - groups
        - openid
        - profile
        - email
      field_map:
        user_identifier: email
        email: email
        firstname: name
        lastname: family_name
        user_groups: groups
      admin_mapping:
        admin_group_regex: ^wgportal-adminsa@mydomain\.net$
```

Tried dropping user from table, bus still same:
```
root@vpn-01:/home/jusbln# sqlite3 /opt/wg-portal/data/sqlite.db
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite> select * from users where email='j.balinskas@mydomain.net';
_WG_SYS_ADMIN_|_WG_SYS_ADMIN_|2025-01-20 21:47:58.779527295+02:00|2025-01-20 21:47:58.783061215+02:00|j.balinskas@mydomain.net|j.balinskas@mydomain.net|oauth|dex-google|0|Justinas Balinskas|||||||||||
sqlite> delete from users where email='j.balinskas@mydomain.net';
sqlite>

**Comment by bonddim** [comment]
> Still getting this log message:
> `Jan 20 21:47:59 vpn-01 wg-portal-amd64[2868754]: {"level":"trace","msg":"registered user j.balinskas@mydomain.net from external authentication provider, admin user: false","time":"2025-01-20T21:47:59+02:00"}`
> 
> My config now looks ike:
> ```
> oidc:
>     - id: dex
>       provider_name: dex-google
>       display_name: Google
>       base_url: https://dex.mydomain.net
>       client_id: REDACTED
>       client_secret: REDACTED
>       extra_scopes:
>         - groups
>         - openid
>         - profile
>         - email
>       field_map:
>         user_identifier: email
>         email: email
>         firstname: name
>         lastname: family_name
>         user_groups: groups
>       admin_mapping:
>         admin_group_regex: ^wgportal-adminsa@mydomain\.net$
> ```
> 
> Tried dropping user from table, bus still same:
> ```
> root@vpn-01:/home/jusbln# sqlite3 /opt/wg-portal/data/sqlite.db
> SQLite version 3.40.1 2022-12-28 14:03:47
> Enter ".help" for usage hints.
> sqlite> select * from users where email='j.balinskas@mydomain.net';
> _WG_SYS_ADMIN_|_WG_SYS_ADMIN_|2025-01-20 21:47:58.779527295+02:00|2025-01-20 21:47:58.783061215+02:00|j.balinskas@mydomain.net|j.balinskas@mydomain.net|oauth|dex-google|0|Justinas Balinskas|||||||||||
> sqlite> delete from users where email='j.balinskas@mydomain.net';
> sqlite>

Do you have typo here only or in config also?

`^wgportal-adminsa@mydomain\.net$` ?

**Comment by justinas-b** [comment]
nope, typo appeared only here in GH issue, while I was redacting sensitive information. There is no typo in config

**Comment by h44z** [comment]
@justinas-b I have just released [v2.0.0-beta.5](https://github.com/h44z/wg-portal/releases/tag/v2.0.0-beta.5) which should fix your issue =)

**Comment by justinas-b** [comment]
Wonderful, thanks a ton @h44z  😊 I can confirm that it works now
